export const pokemons = [
  {
    name: 'bulbasaur',
    number: 1,
    height: 7,
    weight: 69,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/1.gif',
  },
  {
    name: 'ivysaur',
    number: 2,
    height: 10,
    weight: 130,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/2.gif',
  },
  {
    name: 'venusaur',
    number: 3,
    height: 20,
    weight: 1000,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/3.gif',
  },
  {
    name: 'charmander',
    number: 4,
    height: 6,
    weight: 85,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/4.gif',
  },
  {
    name: 'charmeleon',
    number: 5,
    height: 11,
    weight: 190,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/5.gif',
  },
  {
    name: 'charizard',
    number: 6,
    height: 17,
    weight: 905,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/6.gif',
  },
  {
    name: 'squirtle',
    number: 7,
    height: 5,
    weight: 90,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/7.gif',
  },
  {
    name: 'wartortle',
    number: 8,
    height: 10,
    weight: 225,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/8.gif',
  },
  {
    name: 'blastoise',
    number: 9,
    height: 16,
    weight: 855,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/9.gif',
  },
  {
    name: 'caterpie',
    number: 10,
    height: 3,
    weight: 29,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/10.gif',
  },
  {
    name: 'metapod',
    number: 11,
    height: 7,
    weight: 99,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/11.gif',
  },
  {
    name: 'butterfree',
    number: 12,
    height: 11,
    weight: 320,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/12.gif',
  },
  {
    name: 'weedle',
    number: 13,
    height: 3,
    weight: 32,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/13.gif',
  },
  {
    name: 'kakuna',
    number: 14,
    height: 6,
    weight: 100,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/14.gif',
  },
  {
    name: 'beedrill',
    number: 15,
    height: 10,
    weight: 295,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/15.gif',
  },
  {
    name: 'pidgey',
    number: 16,
    height: 3,
    weight: 18,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/16.gif',
  },
  {
    name: 'pidgeotto',
    number: 17,
    height: 11,
    weight: 300,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/17.gif',
  },
  {
    name: 'pidgeot',
    number: 18,
    height: 15,
    weight: 395,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/18.gif',
  },
  {
    name: 'rattata',
    number: 19,
    height: 3,
    weight: 35,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/19.gif',
  },
  {
    name: 'raticate',
    number: 20,
    height: 7,
    weight: 185,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/20.gif',
  },
  {
    name: 'spearow',
    number: 21,
    height: 3,
    weight: 20,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/21.gif',
  },
  {
    name: 'fearow',
    number: 22,
    height: 12,
    weight: 380,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/22.gif',
  },
  {
    name: 'ekans',
    number: 23,
    height: 20,
    weight: 69,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/23.gif',
  },
  {
    name: 'arbok',
    number: 24,
    height: 35,
    weight: 650,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/24.gif',
  },
  {
    name: 'pikachu',
    number: 25,
    height: 4,
    weight: 60,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/25.gif',
  },
  {
    name: 'raichu',
    number: 26,
    height: 8,
    weight: 300,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/26.gif',
  },
  {
    name: 'sandshrew',
    number: 27,
    height: 6,
    weight: 120,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/27.gif',
  },
  {
    name: 'sandslash',
    number: 28,
    height: 10,
    weight: 295,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/28.gif',
  },
  {
    name: 'nidoran-f',
    number: 29,
    height: 4,
    weight: 70,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/29.gif',
  },
  {
    name: 'nidorina',
    number: 30,
    height: 8,
    weight: 200,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/30.gif',
  },
  {
    name: 'nidoqueen',
    number: 31,
    height: 13,
    weight: 600,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/31.gif',
  },
  {
    name: 'nidoran-m',
    number: 32,
    height: 5,
    weight: 90,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/32.gif',
  },
  {
    name: 'nidorino',
    number: 33,
    height: 9,
    weight: 195,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/33.gif',
  },
  {
    name: 'nidoking',
    number: 34,
    height: 14,
    weight: 620,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/34.gif',
  },
  {
    name: 'clefairy',
    number: 35,
    height: 6,
    weight: 75,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/35.gif',
  },
  {
    name: 'clefable',
    number: 36,
    height: 13,
    weight: 400,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/36.gif',
  },
  {
    name: 'vulpix',
    number: 37,
    height: 6,
    weight: 99,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/37.gif',
  },
  {
    name: 'ninetales',
    number: 38,
    height: 11,
    weight: 199,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/38.gif',
  },
  {
    name: 'jigglypuff',
    number: 39,
    height: 5,
    weight: 55,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/39.gif',
  },
  {
    name: 'wigglytuff',
    number: 40,
    height: 10,
    weight: 120,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/40.gif',
  },
  {
    name: 'zubat',
    number: 41,
    height: 8,
    weight: 75,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/41.gif',
  },
  {
    name: 'golbat',
    number: 42,
    height: 16,
    weight: 550,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/42.gif',
  },
  {
    name: 'oddish',
    number: 43,
    height: 5,
    weight: 54,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/43.gif',
  },
  {
    name: 'gloom',
    number: 44,
    height: 8,
    weight: 86,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/44.gif',
  },
  {
    name: 'vileplume',
    number: 45,
    height: 12,
    weight: 186,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/45.gif',
  },
  {
    name: 'paras',
    number: 46,
    height: 3,
    weight: 54,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/46.gif',
  },
  {
    name: 'parasect',
    number: 47,
    height: 10,
    weight: 295,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/47.gif',
  },
  {
    name: 'venonat',
    number: 48,
    height: 10,
    weight: 300,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/48.gif',
  },
  {
    name: 'venomoth',
    number: 49,
    height: 15,
    weight: 125,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/49.gif',
  },
  {
    name: 'diglett',
    number: 50,
    height: 2,
    weight: 8,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/50.gif',
  },
  {
    name: 'dugtrio',
    number: 51,
    height: 7,
    weight: 333,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/51.gif',
  },
  {
    name: 'meowth',
    number: 52,
    height: 4,
    weight: 42,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/52.gif',
  },
  {
    name: 'persian',
    number: 53,
    height: 10,
    weight: 320,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/53.gif',
  },
  {
    name: 'psyduck',
    number: 54,
    height: 8,
    weight: 196,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/54.gif',
  },
  {
    name: 'golduck',
    number: 55,
    height: 17,
    weight: 766,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/55.gif',
  },
  {
    name: 'mankey',
    number: 56,
    height: 5,
    weight: 280,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/56.gif',
  },
  {
    name: 'primeape',
    number: 57,
    height: 10,
    weight: 320,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/57.gif',
  },
  {
    name: 'growlithe',
    number: 58,
    height: 7,
    weight: 190,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/58.gif',
  },
  {
    name: 'arcanine',
    number: 59,
    height: 19,
    weight: 1550,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/59.gif',
  },
  {
    name: 'poliwag',
    number: 60,
    height: 6,
    weight: 124,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/60.gif',
  },
  {
    name: 'poliwhirl',
    number: 61,
    height: 10,
    weight: 200,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/61.gif',
  },
  {
    name: 'poliwrath',
    number: 62,
    height: 13,
    weight: 540,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/62.gif',
  },
  {
    name: 'abra',
    number: 63,
    height: 9,
    weight: 195,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/63.gif',
  },
  {
    name: 'kadabra',
    number: 64,
    height: 13,
    weight: 565,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/64.gif',
  },
  {
    name: 'alakazam',
    number: 65,
    height: 15,
    weight: 480,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/65.gif',
  },
  {
    name: 'machop',
    number: 66,
    height: 8,
    weight: 195,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/66.gif',
  },
  {
    name: 'machoke',
    number: 67,
    height: 15,
    weight: 705,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/67.gif',
  },
  {
    name: 'machamp',
    number: 68,
    height: 16,
    weight: 1300,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/68.gif',
  },
  {
    name: 'bellsprout',
    number: 69,
    height: 7,
    weight: 40,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/69.gif',
  },
  {
    name: 'weepinbell',
    number: 70,
    height: 10,
    weight: 64,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/70.gif',
  },
  {
    name: 'victreebel',
    number: 71,
    height: 17,
    weight: 155,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/71.gif',
  },
  {
    name: 'tentacool',
    number: 72,
    height: 9,
    weight: 455,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/72.gif',
  },
  {
    name: 'tentacruel',
    number: 73,
    height: 16,
    weight: 550,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/73.gif',
  },
  {
    name: 'geodude',
    number: 74,
    height: 4,
    weight: 200,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/74.gif',
  },
  {
    name: 'graveler',
    number: 75,
    height: 10,
    weight: 1050,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/75.gif',
  },
  {
    name: 'golem',
    number: 76,
    height: 14,
    weight: 3000,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/76.gif',
  },
  {
    name: 'ponyta',
    number: 77,
    height: 10,
    weight: 300,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/77.gif',
  },
  {
    name: 'rapidash',
    number: 78,
    height: 17,
    weight: 950,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/78.gif',
  },
  {
    name: 'slowpoke',
    number: 79,
    height: 12,
    weight: 360,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/79.gif',
  },
  {
    name: 'slowbro',
    number: 80,
    height: 16,
    weight: 785,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/80.gif',
  },
  {
    name: 'magnemite',
    number: 81,
    height: 3,
    weight: 60,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/81.gif',
  },
  {
    name: 'magneton',
    number: 82,
    height: 10,
    weight: 600,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/82.gif',
  },
  {
    name: 'farfetchd',
    number: 83,
    height: 8,
    weight: 150,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/83.gif',
  },
  {
    name: 'doduo',
    number: 84,
    height: 14,
    weight: 392,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/84.gif',
  },
  {
    name: 'dodrio',
    number: 85,
    height: 18,
    weight: 852,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/85.gif',
  },
  {
    name: 'seel',
    number: 86,
    height: 11,
    weight: 900,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/86.gif',
  },
  {
    name: 'dewgong',
    number: 87,
    height: 17,
    weight: 1200,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/87.gif',
  },
  {
    name: 'grimer',
    number: 88,
    height: 9,
    weight: 300,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/88.gif',
  },
  {
    name: 'muk',
    number: 89,
    height: 12,
    weight: 300,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/89.gif',
  },
  {
    name: 'shellder',
    number: 90,
    height: 3,
    weight: 40,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/90.gif',
  },
  {
    name: 'cloyster',
    number: 91,
    height: 15,
    weight: 1325,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/91.gif',
  },
  {
    name: 'gastly',
    number: 92,
    height: 13,
    weight: 1,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/92.gif',
  },
  {
    name: 'haunter',
    number: 93,
    height: 16,
    weight: 1,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/93.gif',
  },
  {
    name: 'gengar',
    number: 94,
    height: 15,
    weight: 405,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/94.gif',
  },
  {
    name: 'onix',
    number: 95,
    height: 88,
    weight: 2100,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/95.gif',
  },
  {
    name: 'drowzee',
    number: 96,
    height: 10,
    weight: 324,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/96.gif',
  },
  {
    name: 'hypno',
    number: 97,
    height: 16,
    weight: 756,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/97.gif',
  },
  {
    name: 'krabby',
    number: 98,
    height: 4,
    weight: 65,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/98.gif',
  },
  {
    name: 'kingler',
    number: 99,
    height: 13,
    weight: 600,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/99.gif',
  },
  {
    name: 'voltorb',
    number: 100,
    height: 5,
    weight: 104,
    gif: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/showdown/100.gif',
  },
];
